[project]
name = "foo"
version = "0"
dependencies = []

# uncomment for hermetic build
# [build-system]
# build-backend = "setuptools.build_meta"
# requires = ["setuptools == 78.1.0", "wheel == 0.45.1"]
